### ISSUE TITLE
Reference names termination

### ISSUE THREAD

**Issue by Ygg01** [Ygg01/xml5_draft#5]
How long do we want to reference names?

Right now current XML5 implementation parse until they hit a `;`. That's in my honest opinion too much. Error recovery in that case is moot because if for example I wrote:

```
   <z link = "&amp forgot to close">...
```

The parser will consider `amp forgot to close">...`  as character reference. I think it would be ok, that we either: 
- Have a set of allowed characters like  [XML 1.1 definition of allowed char names](http://www.w3.org/TR/xml11/#NT-NameStartChar)
- There is a set of delimiting characters that terminate the reference. E.g. ` `,`\n`,`\t`,`<`,`=`,`>`,`&`.

I'm leaning towards first solution since we allowed unquoted value attributes like `<a attr=&amp foo=bar>`, but in theory both could work.

**Comment by annevk** [comment]
Both would allow unquoted attributes as far as I can tell.

**Comment by Ygg01** [comment]
This issue is essentially closed, since we're implementing full support for HTML5 named entities and character references.
