### ISSUE TITLE
Multiple root items 

### ISSUE THREAD

**Issue by Ygg01** [Ygg01/xml5_draft#7]
As I currently understand the spec if for example we have following document:

```
    <a><inner/></a>
    <b></b>
```

Will be parsed (with parse error) into following tree representation:

```
     <a>
      |
      +---- <inner>
```

The `<b>` node is lost, because a Start/End tag in EndPhase is ignored. @annevk is this the desired behavior? Do we perhaps want to emit multiple documents or put `<a>` and `<b>` into another root?

**Comment by annevk** [comment]
I think this is the desired behavior. Multiple roots doesn't work with the DOM.

**Comment by Ygg01** [comment]
It seems to me that multiple elements in XML root is a [common mistake](https://www.google.rs/search?q=xml+multiple+root&ie=utf-8&oe=utf-8&gws_rd=cr&ei=0HcvVoWrM4KmsAGIr7rYBA) that we might take into account, and work around. 

Is there any other way we could achieve such functionality? Maybe by saying that we pause in EndPhase on start/end/empty tag and allow people to get another document? Maybe some field, which points to possible other documents or something.

It seems like a common mistake case we could work around. However I'm fine leaving it as is, if there is no easy answer to it.

**Comment by annevk** [comment]
There's no easy answer that would also work well for browsers. We could append it to the existing root instead. That might make it more obvious?

**Comment by Ygg01** [comment]
I fear that inserting it within the root will cause even more confusion. In my humble opinion it invalidates the rule of least surprise.

I'll leave spec as is and do some "experiments" on xml5ever and see how it goes. I'll close issue for now, hopefully in future they'll be a better solution that browser can support.

Thanks for ideas/thoughts :)
